### ISSUE TITLE
What version of PennMUSH is this intended for?

### ISSUE THREAD

**Issue by jrsteensen** [grapenut/hspace3g#1]
Hello! Just was curious what version of PennMUSH is this intended for? Been looking for a modernized HSpace version for my under development game. Tried to install, IAW instructions provided in the README, and kept getting errors on the make. Using the latest version from the pennmush git.

Thanks!

**Comment by grapenut** [comment]
Hi,

I last built it against the release version, not the github dev version.
What kind of errors did you get? I always have problems with the switch
files not being rebuilt properly.

-Jeremy

**Comment by grapenut** [comment]
HSpace has been updated to work with the latest version of PennMUSH from github.com as of 1/19/2018.
