### ISSUE TITLE
Make issues

### ISSUE THREAD

**Issue by Kimojuno** [grapenut/hspace3g#2]
`
/src/space$ make
cc  -Wno-unused-parameter -DHSPACE -I../.. -I../../hdrs -g -c -o hscmds.o hscmds.c
In file included from hspace.h:63:0,
                 from hscmds.c:2:
../../hdrs/strutil.h: In function ‘exists_in_ss’:
../../hdrs/strutil.h:177:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
../../hdrs/strutil.h:177:3: note: use option -std=c99 or -std=gnu99 to compile your code
hscmds.c: In function ‘cmd_console’:
hscmds.c:25:7: error: ‘SWITCH_ABORT’ undeclared (first use in this function)
hscmds.c:25:7: note: each undeclared identifier is reported only once for each function it appears in
hscmds.c:29:12: error: ‘SWITCH_BURN’ undeclared (first use in this function)
hscmds.c:33:12: error: ‘SWITCH_CLOSEBAY’ undeclared (first use in this function)
hscmds.c:37:12: error: ‘SWITCH_COMBATSTAT’ undeclared (first use in this function)
hscmds.c:41:12: error: ‘SWITCH_COOLDOWN’ undeclared (first use in this function)
hscmds.c:45:12: error: ‘SWITCH_DOCK’ undeclared (first use in this function)
hscmds.c:49:12: error: ‘SWITCH_DUMP’ undeclared (first use in this function)
hscmds.c:53:12: error: ‘SWITCH_ESTATUS’ undeclared (first use in this function)
hscmds.c:57:12: error: ‘SWITCH_ETA’ undeclared (first use in this function)
hscmds.c:65:12: error: ‘SWITCH_FIRE’ undeclared (first use in this function)
hscmds.c:71:12: error: ‘SWITCH_GATE’ undeclared (first use in this function)
hscmds.c:75:12: error: ‘SWITCH_HACK’ undeclared (first use in this function)
hscmds.c:79:12: error: ‘SWITCH_HEADING’ undeclared (first use in this function)
hscmds.c:83:12: error: ‘SWITCH_LAND’ undeclared (first use in this function)
hscmds.c:87:12: error: ‘SWITCH_LAUNCH’ undeclared (first use in this function)
hscmds.c:91:12: error: ‘SWITCH_LINK’ undeclared (first use in this function)
hscmds.c:95:12: error: ‘SWITCH_LOCK’ undeclared (first use in this function)
hscmds.c:99:12: error: ‘SWITCH_MANIFEST’ undeclared (first use in this function)
hscmds.c:103:12: error: ‘SWITCH_NAVMODE’ undeclared (first use in this function)
hscmds.c:107:12: error: ‘SWITCH_OPENBAY’ undeclared (first use in this function)
hscmds.c:111:12: error: ‘SWITCH_PRIMARY’ undeclared (first use in this function)
hscmds.c:115:12: error: ‘SWITCH_PROMPT’ undeclared (first use in this function)
hscmds.c:119:12: error: ‘SWITCH_PVPOFF’ undeclared (first use in this function)
hscmds.c:123:12: error: ‘SWITCH_PVPON’ undeclared (first use in this function)
hscmds.c:127:12: error: ‘SWITCH_QUICKSTAT’ undeclared (first use in this function)
hscmds.c:135:12: error: ‘SWITCH_SCAN’ undeclared (first use in this function)
hscmds.c:139:12: error: ‘SWITCH_SECONDARY’ undeclared (first use in this function)
hscmds.c:143:12: error: ‘SWITCH_SHUNT’ undeclared (first use in this function)
hscmds.c:147:12: error: ‘SWITCH_SPEED’ undeclared (first use in this function)
hscmds.c:151:12: error: ‘SWITCH_SREP’ undeclared (first use in this function)
hscmds.c:155:12: error: ‘SWITCH_STANCE’ undeclared (first use in this function)
hscmds.c:163:12: error: ‘SWITCH_SYSSTAT’ undeclared (first use in this function)
hscmds.c:167:12: error: ‘SWITCH_TAXI’ undeclared (first use in this function)
hscmds.c:171:12: error: ‘SWITCH_TRACTOR’ undeclared (first use in this function)
hscmds.c:175:12: error: ‘SWITCH_UNLINK’ undeclared (first use in this function)
hscmds.c:179:12: error: ‘SWITCH_VIEW’ undeclared (first use in this function)
hscmds.c:183:12: error: ‘SWITCH_WAYPOINT’ undeclared (first use in this function)
hscmds.c: In function ‘cmd_space’:
hscmds.c:221:7: error: ‘SWITCH_VERSION’ undeclared (first use in this function)
hscmds.c:223:12: error: ‘SWITCH_DUMP’ undeclared (first use in this function)
hscmds.c:225:12: error: ‘SWITCH_LOAD’ undeclared (first use in this function)
hscmds.c:229:12: error: ‘SWITCH_MOVE’ undeclared (first use in this function)
hscmds.c:231:12: error: ‘SWITCH_RECONFIGURE’ undeclared (first use in this function)
hscmds.c:233:12: error: ‘SWITCH_SPAWN’ undeclared (first use in this function)
hscmds.c:235:12: error: ‘SWITCH_START’ undeclared (first use in this function)
hscmds.c:237:12: error: ‘SWITCH_HALT’ undeclared (first use in this function)
make: *** [hscmds.o] Error 1
`

GCC 4.7 latest Pennmush Version

**Comment by grapenut** [comment]
This is an well known issue with PennMUSH rebuilding the switches.h and switches.c files. It does not include the switches from cmdlocal.c. I added a new file to the repository SWITCHES_SPACE. I would make a copy of the current src/SWITCHES file (e.g. src/SWITCHES_PENN) and then concatenate the two files (and I think it needs to be resorted too).

`cat SWITCHES_PENN SWITCHES_SPACE | sort | uniq > SWITCHES`

Then run make for pennmush. It will fail because hspace isn't built yet, but it will rebuild the switches.h file. Then go to space and make, then come back to pennmush and make.

**Comment by grapenut** [comment]
The other issue that crops up is that they added another parameter to the safe_atr_value() function. It requires a string label as a second argument now.

**Comment by Kimojuno** [comment]
Yup, ran into that issue.

`/src/space$ make
cc  -Wno-unused-parameter -DHSPACE -I../.. -I../../hdrs -g -std=c99 -c -o hsconsole.o hsconsole.c
hsconsole.c: In function ‘set_navmode’:
hsconsole.c:1223:67: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
hsconsole.c: In function ‘add_equipment’:
hsconsole.c:1389:3: error: too few arguments to function ‘safe_atr_value’
In file included from hspace.h:56:0,
                 from hsconsole.c:2:
../../hdrs/attrib.h:111:7: note: declared here
hsconsole.c: In function ‘add_missionitem’:
hsconsole.c:1486:3: error: too few arguments to function ‘safe_atr_value’
In file included from hspace.h:56:0,
                 from hsconsole.c:2:
../../hdrs/attrib.h:111:7: note: declared here
hsconsole.c: In function ‘has_mission’:
hsconsole.c:1536:3: error: too few arguments to function ‘safe_atr_value’
In file included from hspace.h:56:0,
                 from hsconsole.c:2:
../../hdrs/attrib.h:111:7: note: declared here
hsconsole.c: In function ‘has_missionitem’:
hsconsole.c:1577:3: error: too few arguments to function ‘safe_atr_value’
In file included from hspace.h:56:0,
                 from hsconsole.c:2:
../../hdrs/attrib.h:111:7: note: declared here
hsconsole.c: In function ‘sensor_scan’:
hsconsole.c:3730:29: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
hsconsole.c:3739:29: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
hsconsole.c:3859:5: error: too few arguments to function ‘safe_atr_value’
In file included from hspace.h:56:0,
                 from hsconsole.c:2:
../../hdrs/attrib.h:111:7: note: declared here
make: *** [hsconsole.o] Error 1
`

**Comment by grapenut** [comment]
I'm updating everything to compile with the current version of pennmush. I'll push the changes later and update you.

**Comment by grapenut** [comment]
Ok, I've update the repo to work with the latest version of PennMUSH from git. The installation instructions have changed slightly, so it's worth making a new clone of hspace and doing it from scratch. In particular, hspace.cnf goes in pennmush/game/ now, not in pennmush/game/space/.

**Comment by Kimojuno** [comment]
It worked. Thank you so much!
